In [41]:
import requests
import pandas as pd
pd.set_option('display.max.columns', None)

In [25]:
def return_response(uri):
    r = requests.get(uri)
    return r.json()

In [26]:
def return_df(uri):
    
    json_data = return_response(uri)
    
    overview = pd.json_normalize(json_data).drop("network.stations", axis = 1)
    
    inner_net_specific_overview = pd.json_normalize(json_data['network']['stations'])

    return pd.merge(overview, inner_net_specific_overview, how = 'cross')

In [27]:
net_specific_uri_v1 = 'https://api.citybik.es/v2/networks/acces-velo-saguenay'
net_specific_uri_v2 = 'https://api.citybik.es/v2/networks/abu-dhabi-careem-bike'

net_general_uri = 'https://api.citybik.es/v2/networks/'

In [42]:
net_specific_overview_1 = return_df(net_specific_uri_v1)
net_specific_overview_1[:2]

,network.id,network.name,network.location.latitude,network.location.longitude,network.location.city,network.location.country,network.href,network.company,network.gbfs_href,id,name,latitude,longitude,timestamp,free_bikes,empty_slots,extra.uid,extra.renting,extra.returning,extra.last_updated,extra.address,extra.post_code,extra.payment,extra.payment-terminal,extra.altitude,extra.slots,extra.ebikes,extra.has_ebikes,extra.virtual
0,acces-velo-saguenay,Accès Vélo,48.433333,-71.083333,Saguenay,CA,/v2/networks/acces-velo-saguenay,[PBSC Urban Solutions],https://saguenay.publicbikesystem.net/customer...,0b1c0c48e94fae24b1a38f4559a5985a,UQAC,48.42048,-71.053380,2025-06-11T13:03:34.467438+00:00Z,1,5,2,True,True,1749646982,UQAC,0000,"[key, transitcard, creditcard, phone]",True,NaN,7,1,True,False
1,acces-velo-saguenay,Accès Vélo,48.433333,-71.083333,Saguenay,CA,/v2/networks/acces-velo-saguenay,[PBSC Urban Solutions],https://saguenay.publicbikesystem.net/customer...,138fa8c4b31f783bd4af0afb3151df37,Terminus Ste-Therese,48.43268,-71.175537,2025-06-11T13:03:34.467683+00:00Z,0,4,17,True,True,1749646939,Treminus Ste-Therese,G7J1G8,"[key, transitcard, creditcard, phone]",True,0.0,7,0,True,False

In [43]:
net_specific_overview_2 = return_df(net_specific_uri_v2)
net_specific_overview_2[:2]

,network.id,network.name,network.location.latitude,network.location.longitude,network.location.city,network.location.country,network.href,network.company,network.gbfs_href,id,name,latitude,longitude,timestamp,free_bikes,empty_slots,extra.uid,extra.renting,extra.returning,extra.last_updated,extra.address,extra.post_code,extra.payment,extra.payment-terminal,extra.altitude,extra.slots,extra.rental_uris.android,extra.rental_uris.ios,extra.virtual
0,abu-dhabi-careem-bike,Abu Dhabi Careem BIKE,24.4866,54.3728,Abu Dhabi,AE,/v2/networks/abu-dhabi-careem-bike,[Careem],https://dubai.publicbikesystem.net/customer/gb...,004f9aea9391c0a3197981c85926fdb1,AUH - Marasy,24.451202,54.334510,2025-06-11T13:03:26.510391+00:00Z,1,7,113,True,True,1749646964,AUH AL BATEEN,AUH,"[key, transitcard, creditcard, phone]",True,0.0,8,careem://bike.careem.com/station?id=113,careem://bike.careem.com/station?id=113,False
1,abu-dhabi-careem-bike,Abu Dhabi Careem BIKE,24.4866,54.3728,Abu Dhabi,AE,/v2/networks/abu-dhabi-careem-bike,[Careem],https://dubai.publicbikesystem.net/customer/gb...,02757a31c3a5fd002b1e5cc8e8dc756d,AUH - Al Zeina,24.456953,54.615754,2025-06-11T13:03:26.510743+00:00Z,1,14,124,True,True,1749646900,AUH AL RAHA,AUH,"[key, transitcard, creditcard, phone]",True,0.0,15,careem://bike.careem.com/station?id=124,careem://bike.careem.com/station?id=124,False

In [44]:
json_data = return_response(net_general_uri)

df_all = pd.json_normalize(json_data['networks'])
df_all[:2]

,id,name,href,company,gbfs_href,location.latitude,location.longitude,location.city,location.country,system,source,ebikes,license.name,license.url,scooters,instances
0,abu-dhabi-careem-bike,Abu Dhabi Careem BIKE,/v2/networks/abu-dhabi-careem-bike,[Careem],https://dubai.publicbikesystem.net/customer/gb...,24.486600,54.372800,Abu Dhabi,AE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,acces-velo-saguenay,Accès Vélo,/v2/networks/acces-velo-saguenay,[PBSC Urban Solutions],https://saguenay.publicbikesystem.net/customer...,48.433333,-71.083333,Saguenay,CA,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
func_info = lambda df: df.info()

In [45]:
net_specific_overview_2.columns

Index(['network.id', 'network.name', 'network.location.latitude',
       'network.location.longitude', 'network.location.city',
       'network.location.country', 'network.href', 'network.company',
       'network.gbfs_href', 'id', 'name', 'latitude', 'longitude', 'timestamp',
       'free_bikes', 'empty_slots', 'extra.uid', 'extra.renting',
       'extra.returning', 'extra.last_updated', 'extra.address',
       'extra.post_code', 'extra.payment', 'extra.payment-terminal',
       'extra.altitude', 'extra.slots', 'extra.rental_uris.android',
       'extra.rental_uris.ios', 'extra.virtual'],
      dtype='object')

In [36]:
func_info(net_specific_overview_2)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22 entries, 0 to 21
Data columns (total 29 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   network.id                  22 non-null     object
 1   network.name                22 non-null     object
 2   network.location.latitude   22 non-null     float64
 3   network.location.longitude  22 non-null     float64
 4   network.location.city       22 non-null     object
 5   network.location.country    22 non-null     object
 6   network.href                22 non-null     object
 7   network.company             22 non-null     object
 8   network.gbfs_href           22 non-null     object
 9   id                          22 non-null     object
 10  name                        22 non-null     object
 11  latitude                    22 non-null     float64
 12  longitude                   22 non-null     float64
 13  timestamp                   22 non-null     object
 14  free_bikes                  22 non-null     int64
 15  empty_slots                 22 non-null     int64
 16  extra.uid                   22 non-null     object
 17  extra.renting               22 non-null     bool
 18  extra.returning             22 non-null     bool
 19  extra.last_updated          22 non-null     int64
 20  extra.address               22 non-null     object
 21  extra.post_code             22 non-null     object
 22  extra.payment               22 non-null     object
 23  extra.payment-terminal      22 non-null     bool
 24  extra.altitude              21 non-null     float64
 25  extra.slots                 22 non-null     int64
 26  extra.rental_uris.android   22 non-null     object
 27  extra.rental_uris.ios       22 non-null     object
 28  extra.virtual               22 non-null     bool
dtypes: bool(4), float64(5), int64(4), object(16)
memory usage: 4.6+ KB

In [37]:
func_info(net_specific_overview_1)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14 entries, 0 to 13
Data columns (total 29 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   network.id                  14 non-null     object
 1   network.name                14 non-null     object
 2   network.location.latitude   14 non-null     float64
 3   network.location.longitude  14 non-null     float64
 4   network.location.city       14 non-null     object
 5   network.location.country    14 non-null     object
 6   network.href                14 non-null     object
 7   network.company             14 non-null     object
 8   network.gbfs_href           14 non-null     object
 9   id                          14 non-null     object
 10  name                        14 non-null     object
 11  latitude                    14 non-null     float64
 12  longitude                   14 non-null     float64
 13  timestamp                   14 non-null     object
 14  free_bikes                  14 non-null     int64
 15  empty_slots                 14 non-null     int64
 16  extra.uid                   14 non-null     object
 17  extra.renting               14 non-null     bool
 18  extra.returning             14 non-null     bool
 19  extra.last_updated          14 non-null     int64
 20  extra.address               10 non-null     object
 21  extra.post_code             13 non-null     object
 22  extra.payment               14 non-null     object
 23  extra.payment-terminal      14 non-null     bool
 24  extra.altitude              9 non-null      float64
 25  extra.slots                 14 non-null     int64
 26  extra.ebikes                14 non-null     int64
 27  extra.has_ebikes            14 non-null     bool
 28  extra.virtual               14 non-null     bool
dtypes: bool(5), float64(5), int64(5), object(14)
memory usage: 2.8+ KB

In [35]:
func_info(df_all)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 782 entries, 0 to 781
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  782 non-null    object
 1   name                782 non-null    object
 2   href                782 non-null    object
 3   company             782 non-null    object
 4   gbfs_href           231 non-null    object
 5   location.latitude   782 non-null    float64
 6   location.longitude  782 non-null    float64
 7   location.city       782 non-null    object
 8   location.country    782 non-null    object
 9   system              549 non-null    object
 10  source              203 non-null    object
 11  ebikes              45 non-null     object
 12  license.name        72 non-null     object
 13  license.url         72 non-null     object
 14  scooters            2 non-null      object
 15  instances           1 non-null      object
dtypes: float64(2), object(14)
memory usage: 97.9+ KB